### ISSUE TITLE
CSS - user-select: none; prevents copy?

### ISSUE THREAD

**Issue by JohnRSim** [Inndy/vue-clipboard2#11]
If this code is in place on the document then you cannot use copy feature? 

```CSS
* {
	user-select: none;
}
```

Have tried to use this on selections but it did not work - I'm guessing the clipboard script is pasting the data somewhere in the DOM copying and removing?

```CSS
.enableSelection {
	user-select:text;
}
```
